language: go

go:
  - "1.10"

script:
  - make

after_success:
  - VERSION=${TRAVIS_TAG:-snapshot} make -e release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
